<?xml version="1.0"?>
<package format="3">
  <name>trolley_description</name>
  <version>0.0.1</version>
  <description>URDF/Xacro and launch files for the trolley robot</description>

  <maintainer email="your_email@newcastle.edu.au">Jayden</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>xacro</depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz2</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
