/**
 * @file av1.c
 *
 * @brief This source file was generated by cantools version 40.2.3 Tue Aug 26 12:51:21 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "av1.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int av1_auto_mode_pack(
    uint8_t *dst_p,
    const struct av1_auto_mode_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->auto_mode, 0u, 0x01u);

    return (1);
}

int av1_auto_mode_unpack(
    struct av1_auto_mode_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->auto_mode = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_auto_mode_init(struct av1_auto_mode_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_auto_mode_t));

    return 0;
}

uint8_t av1_auto_mode_auto_mode_encode(double value)
{
    return (uint8_t)(value);
}

double av1_auto_mode_auto_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_auto_mode_auto_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_manual_mode_pack(
    uint8_t *dst_p,
    const struct av1_manual_mode_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->manual_mode, 0u, 0x01u);

    return (1);
}

int av1_manual_mode_unpack(
    struct av1_manual_mode_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->manual_mode = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_manual_mode_init(struct av1_manual_mode_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_manual_mode_t));

    return 0;
}

uint8_t av1_manual_mode_manual_mode_encode(double value)
{
    return (uint8_t)(value);
}

double av1_manual_mode_manual_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_manual_mode_manual_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_rc_armed_pack(
    uint8_t *dst_p,
    const struct av1_rc_armed_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rc_armed, 0u, 0x01u);

    return (1);
}

int av1_rc_armed_unpack(
    struct av1_rc_armed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rc_armed = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_rc_armed_init(struct av1_rc_armed_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_rc_armed_t));

    return 0;
}

uint8_t av1_rc_armed_rc_armed_encode(double value)
{
    return (uint8_t)(value);
}

double av1_rc_armed_rc_armed_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_rc_armed_rc_armed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_ros_rpm_request_pack(
    uint8_t *dst_p,
    const struct av1_ros_rpm_request_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->ros_rpm_request, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ros_rpm_request, 8u, 0xffu);

    return (2);
}

int av1_ros_rpm_request_unpack(
    struct av1_ros_rpm_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->ros_rpm_request = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ros_rpm_request |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int av1_ros_rpm_request_init(struct av1_ros_rpm_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_ros_rpm_request_t));

    return 0;
}

uint16_t av1_ros_rpm_request_ros_rpm_request_encode(double value)
{
    return (uint16_t)(value);
}

double av1_ros_rpm_request_ros_rpm_request_decode(uint16_t value)
{
    return ((double)value);
}

bool av1_ros_rpm_request_ros_rpm_request_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

int av1_ros_steer_ang_target_pack(
    uint8_t *dst_p,
    const struct av1_ros_steer_ang_target_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->ros_steer_ang_target, 0u, 0xffu);

    return (1);
}

int av1_ros_steer_ang_target_unpack(
    struct av1_ros_steer_ang_target_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->ros_steer_ang_target = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_ros_steer_ang_target_init(struct av1_ros_steer_ang_target_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_ros_steer_ang_target_t));

    return 0;
}

uint8_t av1_ros_steer_ang_target_ros_steer_ang_target_encode(double value)
{
    return (uint8_t)((value - -90.0) / 0.7);
}

double av1_ros_steer_ang_target_ros_steer_ang_target_decode(uint8_t value)
{
    return (((double)value * 0.7) + -90.0);
}

bool av1_ros_steer_ang_target_ros_steer_ang_target_is_in_range(uint8_t value)
{
    return ((value >= 64u) && (value <= 193u));
}

int av1_steer_ang_actual_pack(
    uint8_t *dst_p,
    const struct av1_steer_ang_actual_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->steer_ang_actual, 0u, 0xffu);

    return (1);
}

int av1_steer_ang_actual_unpack(
    struct av1_steer_ang_actual_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->steer_ang_actual = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_steer_ang_actual_init(struct av1_steer_ang_actual_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_steer_ang_actual_t));

    return 0;
}

uint8_t av1_steer_ang_actual_steer_ang_actual_encode(double value)
{
    return (uint8_t)((value - -90.0) / 0.7);
}

double av1_steer_ang_actual_steer_ang_actual_decode(uint8_t value)
{
    return (((double)value * 0.7) + -90.0);
}

bool av1_steer_ang_actual_steer_ang_actual_is_in_range(uint8_t value)
{
    return ((value >= 64u) && (value <= 193u));
}

int av1_rc_steer_ang_target_pack(
    uint8_t *dst_p,
    const struct av1_rc_steer_ang_target_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rc_steer_ang_target, 0u, 0xffu);

    return (1);
}

int av1_rc_steer_ang_target_unpack(
    struct av1_rc_steer_ang_target_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rc_steer_ang_target = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_rc_steer_ang_target_init(struct av1_rc_steer_ang_target_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_rc_steer_ang_target_t));

    return 0;
}

uint8_t av1_rc_steer_ang_target_rc_steer_ang_target_encode(double value)
{
    return (uint8_t)((value - -90.0) / 0.7);
}

double av1_rc_steer_ang_target_rc_steer_ang_target_decode(uint8_t value)
{
    return (((double)value * 0.7) + -90.0);
}

bool av1_rc_steer_ang_target_rc_steer_ang_target_is_in_range(uint8_t value)
{
    return ((value >= 64u) && (value <= 193u));
}

int av1_brkprs_r_pack(
    uint8_t *dst_p,
    const struct av1_brkprs_r_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->brkprs_r, 0u, 0xffu);

    return (1);
}

int av1_brkprs_r_unpack(
    struct av1_brkprs_r_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->brkprs_r = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_brkprs_r_init(struct av1_brkprs_r_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_brkprs_r_t));

    return 0;
}

uint8_t av1_brkprs_r_brkprs_r_encode(double value)
{
    return (uint8_t)(value / 8.0);
}

double av1_brkprs_r_brkprs_r_decode(uint8_t value)
{
    return ((double)value * 8.0);
}

bool av1_brkprs_r_brkprs_r_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int av1_brkprs_f_pack(
    uint8_t *dst_p,
    const struct av1_brkprs_f_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->brkprs_f, 0u, 0xffu);

    return (1);
}

int av1_brkprs_f_unpack(
    struct av1_brkprs_f_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->brkprs_f = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_brkprs_f_init(struct av1_brkprs_f_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_brkprs_f_t));

    return 0;
}

uint8_t av1_brkprs_f_brkprs_f_encode(double value)
{
    return (uint8_t)(value / 8.0);
}

double av1_brkprs_f_brkprs_f_decode(uint8_t value)
{
    return ((double)value * 8.0);
}

bool av1_brkprs_f_brkprs_f_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int av1_rc_brk_request_pack(
    uint8_t *dst_p,
    const struct av1_rc_brk_request_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rc_brk_request, 0u, 0xffu);

    return (1);
}

int av1_rc_brk_request_unpack(
    struct av1_rc_brk_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rc_brk_request = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_rc_brk_request_init(struct av1_rc_brk_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_rc_brk_request_t));

    return 0;
}

uint8_t av1_rc_brk_request_rc_brk_request_encode(double value)
{
    return (uint8_t)(value / 8.0);
}

double av1_rc_brk_request_rc_brk_request_decode(uint8_t value)
{
    return ((double)value * 8.0);
}

bool av1_rc_brk_request_rc_brk_request_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int av1_ros_rmotor_rpm_request_pack(
    uint8_t *dst_p,
    const struct av1_ros_rmotor_rpm_request_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->ros_rmotor_rpm_request, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ros_rmotor_rpm_request, 8u, 0xffu);

    return (2);
}

int av1_ros_rmotor_rpm_request_unpack(
    struct av1_ros_rmotor_rpm_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->ros_rmotor_rpm_request = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ros_rmotor_rpm_request |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int av1_ros_rmotor_rpm_request_init(struct av1_ros_rmotor_rpm_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_ros_rmotor_rpm_request_t));

    return 0;
}

uint16_t av1_ros_rmotor_rpm_request_ros_rmotor_rpm_request_encode(double value)
{
    return (uint16_t)(value);
}

double av1_ros_rmotor_rpm_request_ros_rmotor_rpm_request_decode(uint16_t value)
{
    return ((double)value);
}

bool av1_ros_rmotor_rpm_request_ros_rmotor_rpm_request_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

int av1_ros_lmotor_rpm_request_pack(
    uint8_t *dst_p,
    const struct av1_ros_lmotor_rpm_request_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->ros_lmotor_rpm_request, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ros_lmotor_rpm_request, 8u, 0xffu);

    return (2);
}

int av1_ros_lmotor_rpm_request_unpack(
    struct av1_ros_lmotor_rpm_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->ros_lmotor_rpm_request = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ros_lmotor_rpm_request |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int av1_ros_lmotor_rpm_request_init(struct av1_ros_lmotor_rpm_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_ros_lmotor_rpm_request_t));

    return 0;
}

uint16_t av1_ros_lmotor_rpm_request_ros_lmotor_rpm_request_encode(double value)
{
    return (uint16_t)(value);
}

double av1_ros_lmotor_rpm_request_ros_lmotor_rpm_request_decode(uint16_t value)
{
    return ((double)value);
}

bool av1_ros_lmotor_rpm_request_ros_lmotor_rpm_request_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

int av1_rc_throttle_request_pack(
    uint8_t *dst_p,
    const struct av1_rc_throttle_request_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rc_throttle_request, 0u, 0xffu);

    return (1);
}

int av1_rc_throttle_request_unpack(
    struct av1_rc_throttle_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rc_throttle_request = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_rc_throttle_request_init(struct av1_rc_throttle_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_rc_throttle_request_t));

    return 0;
}

uint8_t av1_rc_throttle_request_rc_throttle_request_encode(double value)
{
    return (uint8_t)(value / 0.4);
}

double av1_rc_throttle_request_rc_throttle_request_decode(uint8_t value)
{
    return ((double)value * 0.4);
}

bool av1_rc_throttle_request_rc_throttle_request_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int av1_pwm_request_pack(
    uint8_t *dst_p,
    const struct av1_pwm_request_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->pwm_request, 0u, 0xffu);

    return (1);
}

int av1_pwm_request_unpack(
    struct av1_pwm_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->pwm_request = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int av1_pwm_request_init(struct av1_pwm_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_pwm_request_t));

    return 0;
}

uint8_t av1_pwm_request_pwm_request_encode(double value)
{
    return (uint8_t)((value - 50.0) / 0.4);
}

double av1_pwm_request_pwm_request_decode(uint8_t value)
{
    return (((double)value * 0.4) + 50.0);
}

bool av1_pwm_request_pwm_request_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int av1_estop_remote_pack(
    uint8_t *dst_p,
    const struct av1_estop_remote_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->estop_remote, 0u, 0x01u);

    return (1);
}

int av1_estop_remote_unpack(
    struct av1_estop_remote_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->estop_remote = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_estop_remote_init(struct av1_estop_remote_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_estop_remote_t));

    return 0;
}

uint8_t av1_estop_remote_estop_remote_encode(double value)
{
    return (uint8_t)(value);
}

double av1_estop_remote_estop_remote_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_estop_remote_estop_remote_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_estop_car_pack(
    uint8_t *dst_p,
    const struct av1_estop_car_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->estop_car, 0u, 0x01u);

    return (1);
}

int av1_estop_car_unpack(
    struct av1_estop_car_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->estop_car = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_estop_car_init(struct av1_estop_car_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_estop_car_t));

    return 0;
}

uint8_t av1_estop_car_estop_car_encode(double value)
{
    return (uint8_t)(value);
}

double av1_estop_car_estop_car_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_estop_car_estop_car_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_hb_ben_pack(
    uint8_t *dst_p,
    const struct av1_hb_ben_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->hb_ben, 0u, 0x01u);

    return (1);
}

int av1_hb_ben_unpack(
    struct av1_hb_ben_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->hb_ben = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_hb_ben_init(struct av1_hb_ben_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_hb_ben_t));

    return 0;
}

uint8_t av1_hb_ben_hb_ben_encode(double value)
{
    return (uint8_t)(value);
}

double av1_hb_ben_hb_ben_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_hb_ben_hb_ben_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_hb_sen_pack(
    uint8_t *dst_p,
    const struct av1_hb_sen_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->hb_sen, 0u, 0x01u);

    return (1);
}

int av1_hb_sen_unpack(
    struct av1_hb_sen_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->hb_sen = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_hb_sen_init(struct av1_hb_sen_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_hb_sen_t));

    return 0;
}

uint8_t av1_hb_sen_hb_sen_encode(double value)
{
    return (uint8_t)(value);
}

double av1_hb_sen_hb_sen_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_hb_sen_hb_sen_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_hb_ren_pack(
    uint8_t *dst_p,
    const struct av1_hb_ren_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->hb_ren, 0u, 0x01u);

    return (1);
}

int av1_hb_ren_unpack(
    struct av1_hb_ren_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->hb_ren = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_hb_ren_init(struct av1_hb_ren_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_hb_ren_t));

    return 0;
}

uint8_t av1_hb_ren_hb_ren_encode(double value)
{
    return (uint8_t)(value);
}

double av1_hb_ren_hb_ren_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_hb_ren_hb_ren_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_hb_lvd_pack(
    uint8_t *dst_p,
    const struct av1_hb_lvd_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->hb_lvd, 0u, 0x01u);

    return (1);
}

int av1_hb_lvd_unpack(
    struct av1_hb_lvd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->hb_lvd = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_hb_lvd_init(struct av1_hb_lvd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_hb_lvd_t));

    return 0;
}

uint8_t av1_hb_lvd_hb_lvd_encode(double value)
{
    return (uint8_t)(value);
}

double av1_hb_lvd_hb_lvd_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_hb_lvd_hb_lvd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_hb_pre_pack(
    uint8_t *dst_p,
    const struct av1_hb_pre_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->hb_pre, 0u, 0x01u);

    return (1);
}

int av1_hb_pre_unpack(
    struct av1_hb_pre_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->hb_pre = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_hb_pre_init(struct av1_hb_pre_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_hb_pre_t));

    return 0;
}

uint8_t av1_hb_pre_hb_pre_encode(double value)
{
    return (uint8_t)(value);
}

double av1_hb_pre_hb_pre_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_hb_pre_hb_pre_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_charge_pack(
    uint8_t *dst_p,
    const struct av1_charge_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->charge, 0u, 0x01u);

    return (1);
}

int av1_charge_unpack(
    struct av1_charge_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->charge = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_charge_init(struct av1_charge_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_charge_t));

    return 0;
}

uint8_t av1_charge_charge_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charge_charge_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charge_charge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_charge_ack_pack(
    uint8_t *dst_p,
    const struct av1_charge_ack_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->charge_ack, 0u, 0x01u);

    return (1);
}

int av1_charge_ack_unpack(
    struct av1_charge_ack_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->charge_ack = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_charge_ack_init(struct av1_charge_ack_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_charge_ack_t));

    return 0;
}

uint8_t av1_charge_ack_charge_ack_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charge_ack_charge_ack_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charge_ack_charge_ack_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_ts_state_pack(
    uint8_t *dst_p,
    const struct av1_ts_state_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->ts_state, 0u, 0x01u);

    return (1);
}

int av1_ts_state_unpack(
    struct av1_ts_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->ts_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int av1_ts_state_init(struct av1_ts_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_ts_state_t));

    return 0;
}

uint8_t av1_ts_state_ts_state_encode(double value)
{
    return (uint8_t)(value);
}

double av1_ts_state_ts_state_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_ts_state_ts_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_msgid_0_x6_b0_pack(
    uint8_t *dst_p,
    const struct av1_msgid_0_x6_b0_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->pack_current, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->pack_current, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->pack_inst_voltage, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->pack_inst_voltage, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->pack_soc, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->relay_state, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->relay_state, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->crc_checksum, 0u, 0xffu);

    return (8);
}

int av1_msgid_0_x6_b0_unpack(
    struct av1_msgid_0_x6_b0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->pack_current = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->pack_current |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->pack_inst_voltage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->pack_inst_voltage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pack_soc = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->relay_state = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->relay_state |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->crc_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int av1_msgid_0_x6_b0_init(struct av1_msgid_0_x6_b0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_msgid_0_x6_b0_t));

    return 0;
}

uint16_t av1_msgid_0_x6_b0_pack_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double av1_msgid_0_x6_b0_pack_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool av1_msgid_0_x6_b0_pack_current_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t av1_msgid_0_x6_b0_pack_inst_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double av1_msgid_0_x6_b0_pack_inst_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool av1_msgid_0_x6_b0_pack_inst_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint8_t av1_msgid_0_x6_b0_pack_soc_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double av1_msgid_0_x6_b0_pack_soc_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool av1_msgid_0_x6_b0_pack_soc_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint16_t av1_msgid_0_x6_b0_relay_state_encode(double value)
{
    return (uint16_t)(value);
}

double av1_msgid_0_x6_b0_relay_state_decode(uint16_t value)
{
    return ((double)value);
}

bool av1_msgid_0_x6_b0_relay_state_is_in_range(uint16_t value)
{
    return (value <= 10u);
}

uint8_t av1_msgid_0_x6_b0_crc_checksum_encode(double value)
{
    return (uint8_t)(value - 1720.0);
}

double av1_msgid_0_x6_b0_crc_checksum_decode(uint8_t value)
{
    return ((double)value + 1720.0);
}

bool av1_msgid_0_x6_b0_crc_checksum_is_in_range(uint8_t value)
{
    return (value <= -1465u);
}

int av1_kelly_motor_status1_left_pack(
    uint8_t *dst_p,
    const struct av1_kelly_motor_status1_left_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->left_speed_rpm_lsb, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->left_speed_rpm_msb, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->left_current_lsb, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->left_current_msb, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->left_voltage_lsb, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->left_voltage_msb, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->left_error_code_lsb, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->left_error_code_msb, 0u, 0xffu);

    return (8);
}

int av1_kelly_motor_status1_left_unpack(
    struct av1_kelly_motor_status1_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->left_speed_rpm_lsb = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->left_speed_rpm_msb = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->left_current_lsb = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->left_current_msb = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->left_voltage_lsb = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->left_voltage_msb = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->left_error_code_lsb = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->left_error_code_msb = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int av1_kelly_motor_status1_left_init(struct av1_kelly_motor_status1_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_kelly_motor_status1_left_t));

    return 0;
}

uint8_t av1_kelly_motor_status1_left_left_speed_rpm_lsb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_left_left_speed_rpm_lsb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_left_left_speed_rpm_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_speed_rpm_msb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_left_left_speed_rpm_msb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_left_left_speed_rpm_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_current_lsb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_left_left_current_lsb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_left_left_current_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_current_msb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_left_left_current_msb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_left_left_current_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_voltage_lsb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_left_left_voltage_lsb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_left_left_voltage_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_voltage_msb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_left_left_voltage_msb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_left_left_voltage_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_error_code_lsb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_left_left_error_code_lsb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_left_left_error_code_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_left_left_error_code_msb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_left_left_error_code_msb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_left_left_error_code_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int av1_kelly_motor_status2_left_pack(
    uint8_t *dst_p,
    const struct av1_kelly_motor_status2_left_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->left_throttle_signal, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->left_controller_temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->left_motor_temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->left_reserved1, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->left_controller_status, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->left_switch_status, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->left_reserved2, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->left_reserved3, 0u, 0xffu);

    return (8);
}

int av1_kelly_motor_status2_left_unpack(
    struct av1_kelly_motor_status2_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->left_throttle_signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->left_controller_temp = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->left_motor_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->left_reserved1 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->left_controller_status = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->left_switch_status = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->left_reserved2 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->left_reserved3 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int av1_kelly_motor_status2_left_init(struct av1_kelly_motor_status2_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_kelly_motor_status2_left_t));

    return 0;
}

uint8_t av1_kelly_motor_status2_left_left_throttle_signal_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_left_left_throttle_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_left_left_throttle_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_controller_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double av1_kelly_motor_status2_left_left_controller_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool av1_kelly_motor_status2_left_left_controller_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_motor_temp_encode(double value)
{
    return (uint8_t)(value - -30.0);
}

double av1_kelly_motor_status2_left_left_motor_temp_decode(uint8_t value)
{
    return ((double)value + -30.0);
}

bool av1_kelly_motor_status2_left_left_motor_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_reserved1_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_left_left_reserved1_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_left_left_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_controller_status_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_left_left_controller_status_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_left_left_controller_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_switch_status_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_left_left_switch_status_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_left_left_switch_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_reserved2_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_left_left_reserved2_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_left_left_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_left_left_reserved3_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_left_left_reserved3_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_left_left_reserved3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int av1_kelly_motor_status1_right_pack(
    uint8_t *dst_p,
    const struct av1_kelly_motor_status1_right_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->right_speed_rpm_lsb, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->right_speed_rpm_msb, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->right_current_lsb, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->right_current_msb, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->right_voltage_lsb, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->right_voltage_msb, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->right_error_code_lsb, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->right_error_code_msb, 0u, 0xffu);

    return (8);
}

int av1_kelly_motor_status1_right_unpack(
    struct av1_kelly_motor_status1_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->right_speed_rpm_lsb = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->right_speed_rpm_msb = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->right_current_lsb = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->right_current_msb = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->right_voltage_lsb = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->right_voltage_msb = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->right_error_code_lsb = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->right_error_code_msb = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int av1_kelly_motor_status1_right_init(struct av1_kelly_motor_status1_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_kelly_motor_status1_right_t));

    return 0;
}

uint8_t av1_kelly_motor_status1_right_right_speed_rpm_lsb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_right_right_speed_rpm_lsb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_right_right_speed_rpm_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_speed_rpm_msb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_right_right_speed_rpm_msb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_right_right_speed_rpm_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_current_lsb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_right_right_current_lsb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_right_right_current_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_current_msb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_right_right_current_msb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_right_right_current_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_voltage_lsb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_right_right_voltage_lsb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_right_right_voltage_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_voltage_msb_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_kelly_motor_status1_right_right_voltage_msb_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_kelly_motor_status1_right_right_voltage_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_error_code_lsb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_right_right_error_code_lsb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_right_right_error_code_lsb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status1_right_right_error_code_msb_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status1_right_right_error_code_msb_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status1_right_right_error_code_msb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int av1_kelly_motor_status2_right_pack(
    uint8_t *dst_p,
    const struct av1_kelly_motor_status2_right_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->right_throttle_signal, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->right_controller_temp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->right_motor_temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->right_reserved1, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->right_controller_status, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->right_switch_status, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->right_reserved2, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->right_reserved3, 0u, 0xffu);

    return (8);
}

int av1_kelly_motor_status2_right_unpack(
    struct av1_kelly_motor_status2_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->right_throttle_signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->right_controller_temp = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->right_motor_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->right_reserved1 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->right_controller_status = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->right_switch_status = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->right_reserved2 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->right_reserved3 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int av1_kelly_motor_status2_right_init(struct av1_kelly_motor_status2_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_kelly_motor_status2_right_t));

    return 0;
}

uint8_t av1_kelly_motor_status2_right_right_throttle_signal_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_right_right_throttle_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_right_right_throttle_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_controller_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double av1_kelly_motor_status2_right_right_controller_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool av1_kelly_motor_status2_right_right_controller_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_motor_temp_encode(double value)
{
    return (uint8_t)(value - -30.0);
}

double av1_kelly_motor_status2_right_right_motor_temp_decode(uint8_t value)
{
    return ((double)value + -30.0);
}

bool av1_kelly_motor_status2_right_right_motor_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_reserved1_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_right_right_reserved1_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_right_right_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_controller_status_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_right_right_controller_status_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_right_right_controller_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_switch_status_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_right_right_switch_status_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_right_right_switch_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_reserved2_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_right_right_reserved2_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_right_right_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_kelly_motor_status2_right_right_reserved3_encode(double value)
{
    return (uint8_t)(value);
}

double av1_kelly_motor_status2_right_right_reserved3_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_kelly_motor_status2_right_right_reserved3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int av1_dcdc_command_pack(
    uint8_t *dst_p,
    const struct av1_dcdc_command_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->dcdc_command, 0u, 0x03u);

    return (1);
}

int av1_dcdc_command_unpack(
    struct av1_dcdc_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->dcdc_command = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    return (0);
}

int av1_dcdc_command_init(struct av1_dcdc_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_dcdc_command_t));

    return 0;
}

uint8_t av1_dcdc_command_dcdc_command_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_command_dcdc_command_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_command_dcdc_command_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

int av1_dcdc_data_pack(
    uint8_t *dst_p,
    const struct av1_dcdc_data_t *src_p,
    size_t size)
{
    uint8_t dcdc_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->dcdc_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->dcdc_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->dcdc_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->dcdc_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_hvil_err, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_water_con, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_stop_error, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_fan_con, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_err_can, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_hard_fault, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_status, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->dcdc_ready, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_over_cur_output, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_low_vol_output, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_over_vol_output, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_low_vol_input, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_over_vol_input, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_over_temp, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->dcdc_warm_temp, 0u, 0x01u);
    dcdc_temp = (uint8_t)src_p->dcdc_temp;
    dst_p[7] |= pack_left_shift_u8(dcdc_temp, 0u, 0xffu);

    return (8);
}

int av1_dcdc_data_unpack(
    struct av1_dcdc_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t dcdc_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->dcdc_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->dcdc_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->dcdc_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->dcdc_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->dcdc_hvil_err = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->dcdc_water_con = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->dcdc_stop_error = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->dcdc_fan_con = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->dcdc_err_can = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->dcdc_hard_fault = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->dcdc_status = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->dcdc_ready = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->dcdc_over_cur_output = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->dcdc_low_vol_output = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->dcdc_over_vol_output = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->dcdc_low_vol_input = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->dcdc_over_vol_input = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->dcdc_over_temp = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->dcdc_warm_temp = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dcdc_temp = unpack_right_shift_u8(src_p[7], 0u, 0xffu);
    dst_p->dcdc_temp = (int8_t)dcdc_temp;

    return (0);
}

int av1_dcdc_data_init(struct av1_dcdc_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_dcdc_data_t));

    return 0;
}

uint16_t av1_dcdc_data_dcdc_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double av1_dcdc_data_dcdc_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool av1_dcdc_data_dcdc_voltage_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint16_t av1_dcdc_data_dcdc_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double av1_dcdc_data_dcdc_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool av1_dcdc_data_dcdc_current_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t av1_dcdc_data_dcdc_hvil_err_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_hvil_err_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_hvil_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_water_con_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_water_con_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_water_con_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_stop_error_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_stop_error_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_stop_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_fan_con_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_fan_con_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_fan_con_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_err_can_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_err_can_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_err_can_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_hard_fault_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_hard_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_hard_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_status_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_status_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_ready_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_over_cur_output_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_over_cur_output_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_over_cur_output_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_low_vol_output_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_low_vol_output_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_low_vol_output_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_over_vol_output_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_over_vol_output_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_over_vol_output_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_low_vol_input_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_low_vol_input_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_low_vol_input_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_over_vol_input_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_over_vol_input_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_over_vol_input_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_over_temp_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_over_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_over_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_dcdc_data_dcdc_warm_temp_encode(double value)
{
    return (uint8_t)(value);
}

double av1_dcdc_data_dcdc_warm_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_dcdc_data_dcdc_warm_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int8_t av1_dcdc_data_dcdc_temp_encode(double value)
{
    return (int8_t)(value - -60.0);
}

double av1_dcdc_data_dcdc_temp_decode(int8_t value)
{
    return ((double)value + -60.0);
}

bool av1_dcdc_data_dcdc_temp_is_in_range(int8_t value)
{
    return (value >= 0);
}

int av1_charger_command_pack(
    uint8_t *dst_p,
    const struct av1_charger_command_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->max_allow_terminal_voltage_high, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->max_allow_terminal_voltage_low, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->max_allow_charge_current_high, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->max_allow_charge_current_low, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->charger_control, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->charging_mode, 0u, 0xffu);

    return (8);
}

int av1_charger_command_unpack(
    struct av1_charger_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_allow_terminal_voltage_high = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->max_allow_terminal_voltage_low = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->max_allow_charge_current_high = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->max_allow_charge_current_low = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->charger_control = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->charging_mode = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int av1_charger_command_init(struct av1_charger_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_charger_command_t));

    return 0;
}

uint8_t av1_charger_command_max_allow_terminal_voltage_high_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_command_max_allow_terminal_voltage_high_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_command_max_allow_terminal_voltage_high_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_command_max_allow_terminal_voltage_low_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_command_max_allow_terminal_voltage_low_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_command_max_allow_terminal_voltage_low_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_command_max_allow_charge_current_high_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_command_max_allow_charge_current_high_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_command_max_allow_charge_current_high_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_command_max_allow_charge_current_low_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_command_max_allow_charge_current_low_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_command_max_allow_charge_current_low_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_command_charger_control_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_command_charger_control_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_command_charger_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_command_charging_mode_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_command_charging_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_command_charging_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int av1_charger_status_pack(
    uint8_t *dst_p,
    const struct av1_charger_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->output_voltage_high, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->output_voltage_low, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->output_current_high, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->output_current_low, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->status_hw_failure, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->status_over_temperature, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->status_incorrect_input_voltage, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->status_battery_disconnect, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->status_comm_timeout, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->reserved_status_bit5, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->reserved_status_bit6, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->reserved_status_bit7, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->temperature, 0u, 0xffu);

    return (8);
}

int av1_charger_status_unpack(
    struct av1_charger_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->output_voltage_high = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->output_voltage_low = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->output_current_high = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->output_current_low = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->status_hw_failure = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->status_over_temperature = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->status_incorrect_input_voltage = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->status_battery_disconnect = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->status_comm_timeout = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->reserved_status_bit5 = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->reserved_status_bit6 = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->reserved_status_bit7 = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->temperature = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int av1_charger_status_init(struct av1_charger_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct av1_charger_status_t));

    return 0;
}

uint8_t av1_charger_status_output_voltage_high_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_status_output_voltage_high_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_status_output_voltage_high_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_status_output_voltage_low_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_status_output_voltage_low_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_status_output_voltage_low_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_status_output_current_high_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_status_output_current_high_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_status_output_current_high_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_status_output_current_low_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double av1_charger_status_output_current_low_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool av1_charger_status_output_current_low_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t av1_charger_status_status_hw_failure_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_status_hw_failure_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_status_hw_failure_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_status_over_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_status_over_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_status_over_temperature_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_status_incorrect_input_voltage_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_status_incorrect_input_voltage_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_status_incorrect_input_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_status_battery_disconnect_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_status_battery_disconnect_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_status_battery_disconnect_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_status_comm_timeout_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_status_comm_timeout_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_status_comm_timeout_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_reserved_status_bit5_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_reserved_status_bit5_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_reserved_status_bit5_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_reserved_status_bit6_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_reserved_status_bit6_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_reserved_status_bit6_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_reserved_status_bit7_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_reserved_status_bit7_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_reserved_status_bit7_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t av1_charger_status_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double av1_charger_status_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool av1_charger_status_temperature_is_in_range(uint8_t value)
{
    return (value <= 215u);
}
