controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: false        

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'




ackermann_steering_controller:
  ros__parameters:
    wheelbase: 1.74
    front_wheel_track: 1.245
    rear_wheel_track: 1.245
    front_wheels_radius: 0.440 # THIS IS DOUBLE THE REAL WHEEL SIZE DUE TO DOUBLE WHEEL RPM FROM KELLY  CONTROLLER 
    rear_wheels_radius: 0.440
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['RRMotor','RLMotor']
    front_wheels_names: ['LSteer',  'RSteer']
    # false for joystick control
    use_stamped_vel: true

    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom

    # false for localalised sim
    enable_odom_tf: false
    
    twist_covariance_diagonal: [0.05, 0.05, 0.0, 0.0, 0.0, 0.5]
    pose_covariance_diagonal: [0.05, 0.05, 0.0, 0.0, 0.0, 0.5]
    position_feedback: true
    publish_rate: 50.0   # Hz, or whatever rate you want

    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.max_acceleration: 2.0
    linear.x.min_acceleration: -2.0
    
        # --- Steering limits ---
    front_steering_joint_names: ['LSteer', 'RSteer']
    steering.max_position: 0.5236  # 30° in radians
    steering.min_position: -0.5236
    steering.max_velocity: 2.0     # rad/s steering rate limit
    steering.max_acceleration: 3.0  # rad/s² steering acceleration limit