controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'




ackermann_steering_controller:
  ros__parameters:
    wheelbase: 1.74
    front_wheel_track: 1.05
    rear_wheel_track: 1.05
    front_wheels_radius: 0.2
    rear_wheels_radius: 0.2
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['RLMotor', 'RRMotor']
    front_wheels_names: ['LSteer', 'RSteer']
    use_stamped_vel: false
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: true

