amcl:
  ros__parameters:
    use_sim_time: true

    # ── Motion model (alphaX) ────────────────────────────────────────────────
    # lower = more trust in odometry (less scatter)
    alpha1: 0.05   # rot1 noise from rot1
    alpha2: 0.05   # rot1 noise from trans
    alpha3: 0.10   # trans noise from trans
    alpha4: 0.10   # trans noise from rot2
    alpha5: 0.05   # rot2 noise

    # how far before we update again (meters/radians)
    update_min_d: 0.10
    update_min_a: 0.05

    # ── Sensor model (likelihood field) ─────────────────────────────────────
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0

    z_hit:   0.55    # weight on “good” hits
    z_short: 0.10    # weight on unexpected short returns
    z_max:   0.05    # weight on max‐range returns
    z_rand:  0.30    # weight on random

    lambda_short: 0.1

    # optionally throw away bad beams (if you have e.g. glass walls)
    do_beamskip: true
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.30
    beam_skip_error_threshold: 0.90

    max_beams:  60   # downsample your scan if it’s huge
    min_particles: 500
    max_particles: 2000
    resample_interval: 2

    # ── Frames & topics ─────────────────────────────────────────────────────
    scan_topic: scan
    map_topic: map
    tf_broadcast: true
    publish_map_odom_transform: true
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    transform_tolerance: 0.2