amcl:
  ros__parameters:
    use_sim_time: true

    # Topics & frames
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"      # rotate about the IMU/pivot
    global_frame_id: "map"

    # ─── Motion model noise (odometry uncertainty) ────────────────────────
    odom_model_type: diff
    alpha1: 0.2    # rot noise during rot
    alpha2: 0.1    # trans noise during rot
    alpha3: 0.1    # trans noise during trans
    alpha4: 0.2    # rot noise during trans

    # ─── Update / resample thresholds ─────────────────────────────────────
    update_min_d: 0.01          # update every 1 cm of travel
    update_min_a: 0.05          # update every ~3° of rotation
    resample_interval: 1        # resample every update

    # ─── Particle cloud (KLD sampling) ────────────────────────────────────
    min_particles: 500
    max_particles: 2000
    kld_err: 0.02
    kld_z: 0.99

    # ─── Laser sensor model ───────────────────────────────────────────────
    laser_max_beams: 60
    laser_min_range: 0.1
    laser_max_range: 10.0
    laser_sigma_hit: 0.2
    laser_z_hit: 0.95
    laser_z_rand: 0.05
    laser_lambda_short: 0.1
    laser_z_short: 0.05
    laser_z_max: 0.05
