# This is an empty file, so that git commits the folder correctlyekf_filter_node:
ekf_filter_node_odom:
  ros__parameters:
    use_sim_time: true
    frequency:  50.0
    two_d_mode: true
    # Wheel odom input
    odom0: /ackermann_steering_controller/odometry
    odom0_config: [
      false, false, false,    # X, Y, Z positions
      false, false, false,    #  roll, pitch, yaw orientations
      true,  true,  false,    #  X, Y, Z linear velocities
      false, false, true,     #  roll, pitch, yaw angular velocities
      false, false, false     #  X, Y, Z linear accelerations
    ]

    # IMU input for orientation
    imu0: /imu
    imu0_config: [
      false, false, false,    # X, Y, Z positions
      false, false, true,     #  roll, pitch, yaw orientations
      false, false, false,    #  X, Y, Z linear velocities
      false, false, true,     #  roll, pitch, yaw angular velocities
      false, false, false     #  X, Y, Z linear accelerations
    ]
    imu0_remove_gravitational_acceleration: true

  # frames
    odom_frame:     odom
    base_link_frame: base_link
    world_frame:    odom

    # make sure to publish the TF
    publish_tf:     false
    publish_odometry_frame: false
    transform_tolerance: 0.2  # tolerate up to 0.5s of “old” transforms


