# This is an empty file, so that git commits the folder correctlyekf_filter_node:
ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency:  10.0
    two_d_mode: true
    # Wheel odom input
    odom0: /ackermann_steering_controller/odometry
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false]
    # IMU input for orientation
    imu0: /imu
    imu0_config:   [false, false, false,
                    true,  true,  true,
                    false, false, false]

  # frames
    odom_frame:     odom
    base_link_frame: base_link
    world_frame:    map

    # make sure to publish the TF
    publish_tf:     true
    publish_odometry_frame: true
    transform_tolerance: 0.2  # tolerate up to 0.5s of “old” transforms