nmea_navsat_driver:
  ros__parameters:
    port: /dev/ttyUSB1
    baud: 115200
    frame_id: gps
    sentence_id: [GGA, RMC, HDT]


# USE
#   ros2 run nmea_navsat_driver nmea_serial_driver   --ros-args --params-file /home/jay/ros2_ws/src/avone/config/gps_test.yaml

   