ekf_filter_node_map:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.2
    print_diagnostics: true
    debug: false
    predict_to_current_time: true
    transform_tolerance: 0.2          # <-- ADDs
   
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    publish_tf:     true
    publish_odometry_frame: false

    odom0: /odometry/local
    odom0_config: [false, false, false,
              false, false, false,
              true,  true,  true,
              false, false, true,
              false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    odom1: /odometry/gps_fixed
    odom1_config: [true,  true,  false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    imu0: /imu
    imu0_config: [false, false, false,    # X, Y, Z positions
                false, false, true,     #  roll, pitch, yaw orientations
                false, false, false,    #  X, Y, Z linear velocities
                false, false, true,     #  roll, pitch, yaw angular velocities
                false, false, false   ]   #  X, Y, Z linear accelerations
   
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    imu0_orientation_covariance: [0.0025, 0.0,    0.0,
                                  0.0,    0.0025, 0.0,
                                  0.0,    0.0,    0.01]      # roll/pitch ≈ 0.05 rad, yaw ≈ 0.1 rad

    imu0_angular_velocity_covariance: [0.01,  0.0,   0.0,
                                       0.0,   0.01,  0.0,
                                       0.0,   0.0,   0.02]   # rad/s variance

    imu0_linear_acceleration_covariance: [0.1,  0.0,   0.0,
                                          0.0,  0.1,   0.0,
                                          0.0,  0.0,   0.2]   # m/s² variance

    # ---- Optional Covariance Rejection Thresholds ----
    # Used to reject IMU messages that are too noisy or inconsistent.
    imu0_pose_rejection_threshold: 0.8
    imu0_twist_rejection_threshold: 0.8
    imu0_linear_acceleration_rejection_threshold: 0.8


