controller_server:
  ros__parameters:

    # ─── local costmap ────────────────────────────────────────────────────────
    local_costmap:
      local_costmap:
        width: 6.0                # was 3.0; needs to cover ±2.42 m
        height: 6.0
        resolution: 0.05
        update_frequency: 10.0
        publish_frequency: 2.0
        robot_base_frame: "base_link"
        use_sim_time: true
        plugins:
          - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
          - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

    global_costmap:
      global_costmap:
        robot_base_frame: "base_link"


    # ─── controller plugin ────────────────────────────────────────────────────
    controller_plugins: ["RegulatedPurePursuit"]

    RegulatedPurePursuit:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_distance:      0.5    # how far ahead on the path to aim
      min_lookahead_distance:  0.1
      max_lookahead_distance:  1.0
      transform_tolerance:     0.1    # seconds
      min_turning_radius:      0.1    # tune to your vehicle
      max_turning_radius:      2.0



    # CURRENTLY USING 
    controller_plugins: ["FollowPath"]

    FollowPath:                            # <-- BT will call “FollowPath”
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      lookahead_distance:      2.0
      min_lookahead_distance:  0.5
      max_lookahead_distance:  4.0

      min_turning_radius:      3.0
      max_turning_radius:      10.0


      transform_tolerance:     0.2
     
      xy_goal_tolerance:       0.10
      yaw_goal_tolerance:      0.20

    # … your local_costmap, planner_server, etc. …