
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_distance:      5.0
      min_lookahead_distance:  0.5
      max_lookahead_distance:  4.0
      transform_tolerance:     0.5
      
 



# nav2_params.yaml
local_costmap:
  ros__parameters:
    plugins: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: pointcloud
      pointcloud:
        data_type: PointCloud2
        topic: /camera/rgbd/points
        marking: true
        clearing: true
        # Optional: filter out very close or distant points
        obstacle_min_range: 0.2
        obstacle_max_range: 5.0

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: true
      publish_voxel_map: true 
      observation_sources: pointcloud
      pointcloud:
        data_type: PointCloud2
        topic: /camera/rgbd/points
        sensor_frame: camera_link         # change to your camera’s TF frame
        marking: true
        clearing: true
        obstacle_min_range: 0.2
        obstacle_max_range: 5.0
        raytrace_min_range: 0.2
        raytrace_max_range: 5.0
      # vertical voxel stack settings
      origin_z: 0.0                       # floor of your robot
      z_resolution: 0.05                  # height of each slice
      z_voxels: 10                        # total slices per column
      min_obstacle_height: 0.1            # ignore points below this
      max_obstacle_height: 2.0            # ignore points above this

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.3

global_costmap:
  ros__parameters:
    # repeat the same plugin blocks as above...
    plugins: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: pointcloud
      pointcloud:
        data_type: PointCloud2
        topic: /camera/rgbd/points
        marking: true
        clearing: true
        # Optional: filter out very close or distant points
        obstacle_min_range: 0.2
        obstacle_max_range: 5.0

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: true
      publish_voxel_map: true 
      observation_sources: pointcloud
      pointcloud:
        data_type: PointCloud2
        topic: /camera/rgbd/points
        sensor_frame: camera_link         # change to your camera’s TF frame
        marking: true
        clearing: true
        obstacle_min_range: 0.2
        obstacle_max_range: 5.0
        raytrace_min_range: 0.2
        raytrace_max_range: 5.0
      # vertical voxel stack settings
      origin_z: 0.0                       # floor of your robot
      z_resolution: 0.05                  # height of each slice
      z_voxels: 10                        # total slices per column
      min_obstacle_height: 0.1            # ignore points below this
      max_obstacle_height: 2.0            # ignore points above this

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.3